apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/andrasmuca/gitops-cert-level-2-examples.git
              revision: HEAD
              directories:
                - path: application-sets/example-apps/*
          - clusters: {}
  template:      
      metadata:
        name: '{{name}}-billing-app'
      spec:
        project: default
        source:
          repoURL: https://github.com/andrasmuca/gitops-cert-level-2-examples.git
          targetRevision: HEAD
          path: ./application-sets/manifests
        destination:
          server: '{{server}}'
          namespace: billing
        syncPolicy:
          syncOptions:
            - CreateNamespace=true  
          automated: 
            prune: true
            selfHeal: true
